import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trello 2.0 clone",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
};

export default RootLayout;
